version: "3"
services:
  node-app:
    build: .
    ports:
      - "8000:8000"
      - "3000:8000"
      - "4000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db:
